create database customer_behaviour;
select * from customer limit 20 ;

-- what is the total revenue generated by the male vs. female customer? 
select gender , SUM(purchase_amount) as revenue from customer group by gender;

-- which customer used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount from customer where discount_applied = 'yes' and purchase_amount >= (select avg(purchase_amount) from customer);

--  which are the top 5 products with the highest average review rating?
select item_purchased , avg(review_rating) as 'Average product rating' from customer  group by item_purchased order by avg(review_rating) desc limit 5;

--  compare the average purchase amount between standard and express shipping?

-- the below code calculate for all shipping types. but we need only for two types. and not round off the last numeric terms of purchase amount. 
-- select shipping_type, avg(purchase_amount) as 'average purchase aumount' from customer group by (shipping_type)
select shipping_type, round(avg(purchase_amount),2) as 'average purchase aumount' from customer where shipping_type in ('Standard','Express') group by (shipping_type);

--  do subscribed customers spend more? compare average spend and total spend revenue between subscribers and non- subscribers?
select  subscription_status , count(customer_id) as total_customer , round(avg(purchase_amount),2) as average_spend , round(sum(purchase_amount),20) as total_spend from customer group by (subscription_status);

--  which 5 products having highest percentage of purchases with discounts applied?
-- what is sub query? 
select item_purchased,round(100 * sum(case when discount_applied = 'yes' then 1 else 0 end)/count(*),2) as discount_rate from customer group by (item_purchased) order by (discount_rate) desc limit 5 ;

--  segment customers into new , returning and loyal based on their total number of previoys purchases, and show the count of each segment.
-- we cte in this 
with customer_type as (select customer_id,previous_purchases, case when previous_purchases = 1 then 'New' when previous_purchases between 2 and 10 then 'Returning' else 'Loyal' end as customer_segment from customer) select customer_segment, count(*) as 'number of customer' from customer_type group by customer_segment;

-- what are the top 3 most purchased products within each category?
-- this is advanced query . so in this we need window functions to run product by total orders within each category.
with item_counts as ( 
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category,item_purchased,total_orders
from item_counts
where item_rank <= 3;

-- WITH item_counts AS (
--     SELECT
--         category,
--         item_purchased,
--         COUNT(customer_id) AS total_orders,
--         ROW_NUMBER() OVER (
--             PARTITION BY category
--             ORDER BY COUNT(customer_id) DESC
--         ) AS item_rank
--     FROM customer
--     GROUP BY category, item_purchased
-- )

-- SELECT
--     item_rank,
--     category,
--     item_purchased,
--     total_orders
-- FROM item_counts
-- WHERE item_rank <= 3;
 
-- are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- what is the revenue contribution of each agr group?
select age_group,
sum(purchase_amount) as total_revenue 
from customer
group by (age_group)
order by total_revenue desc;



